INSERT INTO PRODUCT_DETAILS (PRODUCT_NAME,PRODUCT_COMPANY) VALUES ('Product 1','Product Company 1');
INSERT INTO PRODUCT_DETAILS (PRODUCT_NAME,PRODUCT_COMPANY) VALUES('Product 5','Product Company 2');
INSERT INTO PRODUCT_DETAILS (PRODUCT_NAME,PRODUCT_COMPANY) VALUES ('Product 88','Product Company 3');
INSERT INTO PRODUCT_DETAILS (PRODUCT_NAME,PRODUCT_COMPANY) VALUES ('Product 66','Product Company 4');
INSERT INTO PRODUCT_DETAILS (PRODUCT_NAME,PRODUCT_COMPANY) VALUES('Product 1','Product Company 5');
INSERT INTO PRODUCT_DETAILS (PRODUCT_NAME,PRODUCT_COMPANY) VALUES ('Product 8','Product Company 6');
INSERT INTO PRODUCT_DETAILS (PRODUCT_NAME,PRODUCT_COMPANY) VALUES ('Product 5','Product Company 7');
INSERT INTO PRODUCT_DETAILS (PRODUCT_NAME,PRODUCT_COMPANY) VALUES('Product 6','Product Company 8');
